# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViewDogsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewDogsApp
pod 'Alamofire', '~> 4.5'
pod 'AlamofireNetworkActivityLogger', '~> 2.0'
pod 'AlamofireObjectMapper', '~> 5.0'
pod 'ObjectMapper'
pod 'Kingfisher', '~> 4.0'
pod 'PKHUD', '~> 5.0'
pod 'Agrume'
pod 'SwiftLint'
pod 'EmptyKit'
end
